/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedRevisionRouteImport } from './routes/_authenticated/revision'
import { Route as AuthenticatedReminderRouteImport } from './routes/_authenticated/reminder'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPowerNapRouteImport } from './routes/_authenticated/power-nap'
import { Route as AuthenticatedPomodoroRouteImport } from './routes/_authenticated/pomodoro'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedClassroomRouteImport } from './routes/_authenticated/classroom'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAiCallsRouteImport } from './routes/_authenticated/ai-calls'
import { Route as AuthenticatedRevisionIndexRouteImport } from './routes/_authenticated/revision.index'
import { Route as AuthenticatedClassroomIndexRouteImport } from './routes/_authenticated/classroom.index'
import { Route as AuthenticatedVoiceCallNewRouteImport } from './routes/_authenticated/voice-call.new'
import { Route as AuthenticatedRevisionSetIdRouteImport } from './routes/_authenticated/revision/$setId'
import { Route as AuthenticatedClassroomSettingsRouteImport } from './routes/_authenticated/classroom.settings'
import { Route as AuthenticatedClassroomAssignmentsRouteImport } from './routes/_authenticated/classroom.assignments'
import { Route as AuthenticatedClassroomAnnouncementsRouteImport } from './routes/_authenticated/classroom.announcements'
import { Route as ApiPublicVoiceTurnRouteImport } from './routes/api/public/voice/turn'
import { Route as ApiPublicVoiceStatusRouteImport } from './routes/api/public/voice/status'
import { Route as ApiPublicVoiceStartRouteImport } from './routes/api/public/voice/start'
import { Route as ApiPublicStudyNotesStreamRouteImport } from './routes/api/public/study-notes/stream'
import { Route as ApiPublicHooksVoiceDispatcherRouteImport } from './routes/api/public/hooks/voice-dispatcher'
import { Route as ApiPublicHooksClassroomSyncRouteImport } from './routes/api/public/hooks/classroom-sync'
import { Route as ApiPublicClassroomCallbackRouteImport } from './routes/api/public/classroom/callback'
import { Route as AuthenticatedRevisionSetIdSummaryRouteImport } from './routes/_authenticated/revision/$setId.summary'
import { Route as AuthenticatedRevisionSetIdSessionRouteImport } from './routes/_authenticated/revision/$setId.session'
import { Route as AuthenticatedRevisionSetIdNotesRouteImport } from './routes/_authenticated/revision/$setId.notes'
import { Route as AuthenticatedRevisionSetIdKnownRouteImport } from './routes/_authenticated/revision/$setId.known'
import { Route as AuthenticatedRevisionSetIdFlashcardsRouteImport } from './routes/_authenticated/revision/$setId.flashcards'
import { Route as AuthenticatedRevisionSetIdAskRouteImport } from './routes/_authenticated/revision/$setId.ask'
import { Route as AuthenticatedRevisionSetIdTopicNoteIdRouteImport } from './routes/_authenticated/revision/$setId.topic.$noteId'
import { Route as AuthenticatedRevisionSetIdNotesNewRouteImport } from './routes/_authenticated/revision/$setId.notes.new'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRevisionRoute = AuthenticatedRevisionRouteImport.update({
  id: '/revision',
  path: '/revision',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReminderRoute = AuthenticatedReminderRouteImport.update({
  id: '/reminder',
  path: '/reminder',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPowerNapRoute = AuthenticatedPowerNapRouteImport.update({
  id: '/power-nap',
  path: '/power-nap',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPomodoroRoute = AuthenticatedPomodoroRouteImport.update({
  id: '/pomodoro',
  path: '/pomodoro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClassroomRoute = AuthenticatedClassroomRouteImport.update({
  id: '/classroom',
  path: '/classroom',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiCallsRoute = AuthenticatedAiCallsRouteImport.update({
  id: '/ai-calls',
  path: '/ai-calls',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRevisionIndexRoute =
  AuthenticatedRevisionIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedRevisionRoute,
  } as any)
const AuthenticatedClassroomIndexRoute =
  AuthenticatedClassroomIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedClassroomRoute,
  } as any)
const AuthenticatedVoiceCallNewRoute =
  AuthenticatedVoiceCallNewRouteImport.update({
    id: '/voice-call/new',
    path: '/voice-call/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRevisionSetIdRoute =
  AuthenticatedRevisionSetIdRouteImport.update({
    id: '/$setId',
    path: '/$setId',
    getParentRoute: () => AuthenticatedRevisionRoute,
  } as any)
const AuthenticatedClassroomSettingsRoute =
  AuthenticatedClassroomSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedClassroomRoute,
  } as any)
const AuthenticatedClassroomAssignmentsRoute =
  AuthenticatedClassroomAssignmentsRouteImport.update({
    id: '/assignments',
    path: '/assignments',
    getParentRoute: () => AuthenticatedClassroomRoute,
  } as any)
const AuthenticatedClassroomAnnouncementsRoute =
  AuthenticatedClassroomAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedClassroomRoute,
  } as any)
const ApiPublicVoiceTurnRoute = ApiPublicVoiceTurnRouteImport.update({
  id: '/api/public/voice/turn',
  path: '/api/public/voice/turn',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVoiceStatusRoute = ApiPublicVoiceStatusRouteImport.update({
  id: '/api/public/voice/status',
  path: '/api/public/voice/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVoiceStartRoute = ApiPublicVoiceStartRouteImport.update({
  id: '/api/public/voice/start',
  path: '/api/public/voice/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStudyNotesStreamRoute =
  ApiPublicStudyNotesStreamRouteImport.update({
    id: '/api/public/study-notes/stream',
    path: '/api/public/study-notes/stream',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksVoiceDispatcherRoute =
  ApiPublicHooksVoiceDispatcherRouteImport.update({
    id: '/api/public/hooks/voice-dispatcher',
    path: '/api/public/hooks/voice-dispatcher',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksClassroomSyncRoute =
  ApiPublicHooksClassroomSyncRouteImport.update({
    id: '/api/public/hooks/classroom-sync',
    path: '/api/public/hooks/classroom-sync',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicClassroomCallbackRoute =
  ApiPublicClassroomCallbackRouteImport.update({
    id: '/api/public/classroom/callback',
    path: '/api/public/classroom/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedRevisionSetIdSummaryRoute =
  AuthenticatedRevisionSetIdSummaryRouteImport.update({
    id: '/summary',
    path: '/summary',
    getParentRoute: () => AuthenticatedRevisionSetIdRoute,
  } as any)
const AuthenticatedRevisionSetIdSessionRoute =
  AuthenticatedRevisionSetIdSessionRouteImport.update({
    id: '/session',
    path: '/session',
    getParentRoute: () => AuthenticatedRevisionSetIdRoute,
  } as any)
const AuthenticatedRevisionSetIdNotesRoute =
  AuthenticatedRevisionSetIdNotesRouteImport.update({
    id: '/notes',
    path: '/notes',
    getParentRoute: () => AuthenticatedRevisionSetIdRoute,
  } as any)
const AuthenticatedRevisionSetIdKnownRoute =
  AuthenticatedRevisionSetIdKnownRouteImport.update({
    id: '/known',
    path: '/known',
    getParentRoute: () => AuthenticatedRevisionSetIdRoute,
  } as any)
const AuthenticatedRevisionSetIdFlashcardsRoute =
  AuthenticatedRevisionSetIdFlashcardsRouteImport.update({
    id: '/flashcards',
    path: '/flashcards',
    getParentRoute: () => AuthenticatedRevisionSetIdRoute,
  } as any)
const AuthenticatedRevisionSetIdAskRoute =
  AuthenticatedRevisionSetIdAskRouteImport.update({
    id: '/ask',
    path: '/ask',
    getParentRoute: () => AuthenticatedRevisionSetIdRoute,
  } as any)
const AuthenticatedRevisionSetIdTopicNoteIdRoute =
  AuthenticatedRevisionSetIdTopicNoteIdRouteImport.update({
    id: '/topic/$noteId',
    path: '/topic/$noteId',
    getParentRoute: () => AuthenticatedRevisionSetIdRoute,
  } as any)
const AuthenticatedRevisionSetIdNotesNewRoute =
  AuthenticatedRevisionSetIdNotesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedRevisionSetIdNotesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/welcome': typeof WelcomeRoute
  '/ai-calls': typeof AuthenticatedAiCallsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/chat': typeof AuthenticatedChatRoute
  '/classroom': typeof AuthenticatedClassroomRouteWithChildren
  '/home': typeof AuthenticatedHomeRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/pomodoro': typeof AuthenticatedPomodoroRoute
  '/power-nap': typeof AuthenticatedPowerNapRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reminder': typeof AuthenticatedReminderRoute
  '/revision': typeof AuthenticatedRevisionRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/classroom/announcements': typeof AuthenticatedClassroomAnnouncementsRoute
  '/classroom/assignments': typeof AuthenticatedClassroomAssignmentsRoute
  '/classroom/settings': typeof AuthenticatedClassroomSettingsRoute
  '/revision/$setId': typeof AuthenticatedRevisionSetIdRouteWithChildren
  '/voice-call/new': typeof AuthenticatedVoiceCallNewRoute
  '/classroom/': typeof AuthenticatedClassroomIndexRoute
  '/revision/': typeof AuthenticatedRevisionIndexRoute
  '/revision/$setId/ask': typeof AuthenticatedRevisionSetIdAskRoute
  '/revision/$setId/flashcards': typeof AuthenticatedRevisionSetIdFlashcardsRoute
  '/revision/$setId/known': typeof AuthenticatedRevisionSetIdKnownRoute
  '/revision/$setId/notes': typeof AuthenticatedRevisionSetIdNotesRouteWithChildren
  '/revision/$setId/session': typeof AuthenticatedRevisionSetIdSessionRoute
  '/revision/$setId/summary': typeof AuthenticatedRevisionSetIdSummaryRoute
  '/api/public/classroom/callback': typeof ApiPublicClassroomCallbackRoute
  '/api/public/hooks/classroom-sync': typeof ApiPublicHooksClassroomSyncRoute
  '/api/public/hooks/voice-dispatcher': typeof ApiPublicHooksVoiceDispatcherRoute
  '/api/public/study-notes/stream': typeof ApiPublicStudyNotesStreamRoute
  '/api/public/voice/start': typeof ApiPublicVoiceStartRoute
  '/api/public/voice/status': typeof ApiPublicVoiceStatusRoute
  '/api/public/voice/turn': typeof ApiPublicVoiceTurnRoute
  '/revision/$setId/notes/new': typeof AuthenticatedRevisionSetIdNotesNewRoute
  '/revision/$setId/topic/$noteId': typeof AuthenticatedRevisionSetIdTopicNoteIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/welcome': typeof WelcomeRoute
  '/ai-calls': typeof AuthenticatedAiCallsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/chat': typeof AuthenticatedChatRoute
  '/home': typeof AuthenticatedHomeRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/pomodoro': typeof AuthenticatedPomodoroRoute
  '/power-nap': typeof AuthenticatedPowerNapRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reminder': typeof AuthenticatedReminderRoute
  '/api/chat': typeof ApiChatRoute
  '/classroom/announcements': typeof AuthenticatedClassroomAnnouncementsRoute
  '/classroom/assignments': typeof AuthenticatedClassroomAssignmentsRoute
  '/classroom/settings': typeof AuthenticatedClassroomSettingsRoute
  '/revision/$setId': typeof AuthenticatedRevisionSetIdRouteWithChildren
  '/voice-call/new': typeof AuthenticatedVoiceCallNewRoute
  '/classroom': typeof AuthenticatedClassroomIndexRoute
  '/revision': typeof AuthenticatedRevisionIndexRoute
  '/revision/$setId/ask': typeof AuthenticatedRevisionSetIdAskRoute
  '/revision/$setId/flashcards': typeof AuthenticatedRevisionSetIdFlashcardsRoute
  '/revision/$setId/known': typeof AuthenticatedRevisionSetIdKnownRoute
  '/revision/$setId/notes': typeof AuthenticatedRevisionSetIdNotesRouteWithChildren
  '/revision/$setId/session': typeof AuthenticatedRevisionSetIdSessionRoute
  '/revision/$setId/summary': typeof AuthenticatedRevisionSetIdSummaryRoute
  '/api/public/classroom/callback': typeof ApiPublicClassroomCallbackRoute
  '/api/public/hooks/classroom-sync': typeof ApiPublicHooksClassroomSyncRoute
  '/api/public/hooks/voice-dispatcher': typeof ApiPublicHooksVoiceDispatcherRoute
  '/api/public/study-notes/stream': typeof ApiPublicStudyNotesStreamRoute
  '/api/public/voice/start': typeof ApiPublicVoiceStartRoute
  '/api/public/voice/status': typeof ApiPublicVoiceStatusRoute
  '/api/public/voice/turn': typeof ApiPublicVoiceTurnRoute
  '/revision/$setId/notes/new': typeof AuthenticatedRevisionSetIdNotesNewRoute
  '/revision/$setId/topic/$noteId': typeof AuthenticatedRevisionSetIdTopicNoteIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/welcome': typeof WelcomeRoute
  '/_authenticated/ai-calls': typeof AuthenticatedAiCallsRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/classroom': typeof AuthenticatedClassroomRouteWithChildren
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/pomodoro': typeof AuthenticatedPomodoroRoute
  '/_authenticated/power-nap': typeof AuthenticatedPowerNapRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/reminder': typeof AuthenticatedReminderRoute
  '/_authenticated/revision': typeof AuthenticatedRevisionRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/_authenticated/classroom/announcements': typeof AuthenticatedClassroomAnnouncementsRoute
  '/_authenticated/classroom/assignments': typeof AuthenticatedClassroomAssignmentsRoute
  '/_authenticated/classroom/settings': typeof AuthenticatedClassroomSettingsRoute
  '/_authenticated/revision/$setId': typeof AuthenticatedRevisionSetIdRouteWithChildren
  '/_authenticated/voice-call/new': typeof AuthenticatedVoiceCallNewRoute
  '/_authenticated/classroom/': typeof AuthenticatedClassroomIndexRoute
  '/_authenticated/revision/': typeof AuthenticatedRevisionIndexRoute
  '/_authenticated/revision/$setId/ask': typeof AuthenticatedRevisionSetIdAskRoute
  '/_authenticated/revision/$setId/flashcards': typeof AuthenticatedRevisionSetIdFlashcardsRoute
  '/_authenticated/revision/$setId/known': typeof AuthenticatedRevisionSetIdKnownRoute
  '/_authenticated/revision/$setId/notes': typeof AuthenticatedRevisionSetIdNotesRouteWithChildren
  '/_authenticated/revision/$setId/session': typeof AuthenticatedRevisionSetIdSessionRoute
  '/_authenticated/revision/$setId/summary': typeof AuthenticatedRevisionSetIdSummaryRoute
  '/api/public/classroom/callback': typeof ApiPublicClassroomCallbackRoute
  '/api/public/hooks/classroom-sync': typeof ApiPublicHooksClassroomSyncRoute
  '/api/public/hooks/voice-dispatcher': typeof ApiPublicHooksVoiceDispatcherRoute
  '/api/public/study-notes/stream': typeof ApiPublicStudyNotesStreamRoute
  '/api/public/voice/start': typeof ApiPublicVoiceStartRoute
  '/api/public/voice/status': typeof ApiPublicVoiceStatusRoute
  '/api/public/voice/turn': typeof ApiPublicVoiceTurnRoute
  '/_authenticated/revision/$setId/notes/new': typeof AuthenticatedRevisionSetIdNotesNewRoute
  '/_authenticated/revision/$setId/topic/$noteId': typeof AuthenticatedRevisionSetIdTopicNoteIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/welcome'
    | '/ai-calls'
    | '/analytics'
    | '/chat'
    | '/classroom'
    | '/home'
    | '/notifications'
    | '/pomodoro'
    | '/power-nap'
    | '/profile'
    | '/reminder'
    | '/revision'
    | '/api/chat'
    | '/classroom/announcements'
    | '/classroom/assignments'
    | '/classroom/settings'
    | '/revision/$setId'
    | '/voice-call/new'
    | '/classroom/'
    | '/revision/'
    | '/revision/$setId/ask'
    | '/revision/$setId/flashcards'
    | '/revision/$setId/known'
    | '/revision/$setId/notes'
    | '/revision/$setId/session'
    | '/revision/$setId/summary'
    | '/api/public/classroom/callback'
    | '/api/public/hooks/classroom-sync'
    | '/api/public/hooks/voice-dispatcher'
    | '/api/public/study-notes/stream'
    | '/api/public/voice/start'
    | '/api/public/voice/status'
    | '/api/public/voice/turn'
    | '/revision/$setId/notes/new'
    | '/revision/$setId/topic/$noteId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/welcome'
    | '/ai-calls'
    | '/analytics'
    | '/chat'
    | '/home'
    | '/notifications'
    | '/pomodoro'
    | '/power-nap'
    | '/profile'
    | '/reminder'
    | '/api/chat'
    | '/classroom/announcements'
    | '/classroom/assignments'
    | '/classroom/settings'
    | '/revision/$setId'
    | '/voice-call/new'
    | '/classroom'
    | '/revision'
    | '/revision/$setId/ask'
    | '/revision/$setId/flashcards'
    | '/revision/$setId/known'
    | '/revision/$setId/notes'
    | '/revision/$setId/session'
    | '/revision/$setId/summary'
    | '/api/public/classroom/callback'
    | '/api/public/hooks/classroom-sync'
    | '/api/public/hooks/voice-dispatcher'
    | '/api/public/study-notes/stream'
    | '/api/public/voice/start'
    | '/api/public/voice/status'
    | '/api/public/voice/turn'
    | '/revision/$setId/notes/new'
    | '/revision/$setId/topic/$noteId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/onboarding'
    | '/welcome'
    | '/_authenticated/ai-calls'
    | '/_authenticated/analytics'
    | '/_authenticated/chat'
    | '/_authenticated/classroom'
    | '/_authenticated/home'
    | '/_authenticated/notifications'
    | '/_authenticated/pomodoro'
    | '/_authenticated/power-nap'
    | '/_authenticated/profile'
    | '/_authenticated/reminder'
    | '/_authenticated/revision'
    | '/api/chat'
    | '/_authenticated/classroom/announcements'
    | '/_authenticated/classroom/assignments'
    | '/_authenticated/classroom/settings'
    | '/_authenticated/revision/$setId'
    | '/_authenticated/voice-call/new'
    | '/_authenticated/classroom/'
    | '/_authenticated/revision/'
    | '/_authenticated/revision/$setId/ask'
    | '/_authenticated/revision/$setId/flashcards'
    | '/_authenticated/revision/$setId/known'
    | '/_authenticated/revision/$setId/notes'
    | '/_authenticated/revision/$setId/session'
    | '/_authenticated/revision/$setId/summary'
    | '/api/public/classroom/callback'
    | '/api/public/hooks/classroom-sync'
    | '/api/public/hooks/voice-dispatcher'
    | '/api/public/study-notes/stream'
    | '/api/public/voice/start'
    | '/api/public/voice/status'
    | '/api/public/voice/turn'
    | '/_authenticated/revision/$setId/notes/new'
    | '/_authenticated/revision/$setId/topic/$noteId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
  WelcomeRoute: typeof WelcomeRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiPublicClassroomCallbackRoute: typeof ApiPublicClassroomCallbackRoute
  ApiPublicHooksClassroomSyncRoute: typeof ApiPublicHooksClassroomSyncRoute
  ApiPublicHooksVoiceDispatcherRoute: typeof ApiPublicHooksVoiceDispatcherRoute
  ApiPublicStudyNotesStreamRoute: typeof ApiPublicStudyNotesStreamRoute
  ApiPublicVoiceStartRoute: typeof ApiPublicVoiceStartRoute
  ApiPublicVoiceStatusRoute: typeof ApiPublicVoiceStatusRoute
  ApiPublicVoiceTurnRoute: typeof ApiPublicVoiceTurnRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/revision': {
      id: '/_authenticated/revision'
      path: '/revision'
      fullPath: '/revision'
      preLoaderRoute: typeof AuthenticatedRevisionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reminder': {
      id: '/_authenticated/reminder'
      path: '/reminder'
      fullPath: '/reminder'
      preLoaderRoute: typeof AuthenticatedReminderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/power-nap': {
      id: '/_authenticated/power-nap'
      path: '/power-nap'
      fullPath: '/power-nap'
      preLoaderRoute: typeof AuthenticatedPowerNapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pomodoro': {
      id: '/_authenticated/pomodoro'
      path: '/pomodoro'
      fullPath: '/pomodoro'
      preLoaderRoute: typeof AuthenticatedPomodoroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/classroom': {
      id: '/_authenticated/classroom'
      path: '/classroom'
      fullPath: '/classroom'
      preLoaderRoute: typeof AuthenticatedClassroomRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-calls': {
      id: '/_authenticated/ai-calls'
      path: '/ai-calls'
      fullPath: '/ai-calls'
      preLoaderRoute: typeof AuthenticatedAiCallsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/revision/': {
      id: '/_authenticated/revision/'
      path: '/'
      fullPath: '/revision/'
      preLoaderRoute: typeof AuthenticatedRevisionIndexRouteImport
      parentRoute: typeof AuthenticatedRevisionRoute
    }
    '/_authenticated/classroom/': {
      id: '/_authenticated/classroom/'
      path: '/'
      fullPath: '/classroom/'
      preLoaderRoute: typeof AuthenticatedClassroomIndexRouteImport
      parentRoute: typeof AuthenticatedClassroomRoute
    }
    '/_authenticated/voice-call/new': {
      id: '/_authenticated/voice-call/new'
      path: '/voice-call/new'
      fullPath: '/voice-call/new'
      preLoaderRoute: typeof AuthenticatedVoiceCallNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/revision/$setId': {
      id: '/_authenticated/revision/$setId'
      path: '/$setId'
      fullPath: '/revision/$setId'
      preLoaderRoute: typeof AuthenticatedRevisionSetIdRouteImport
      parentRoute: typeof AuthenticatedRevisionRoute
    }
    '/_authenticated/classroom/settings': {
      id: '/_authenticated/classroom/settings'
      path: '/settings'
      fullPath: '/classroom/settings'
      preLoaderRoute: typeof AuthenticatedClassroomSettingsRouteImport
      parentRoute: typeof AuthenticatedClassroomRoute
    }
    '/_authenticated/classroom/assignments': {
      id: '/_authenticated/classroom/assignments'
      path: '/assignments'
      fullPath: '/classroom/assignments'
      preLoaderRoute: typeof AuthenticatedClassroomAssignmentsRouteImport
      parentRoute: typeof AuthenticatedClassroomRoute
    }
    '/_authenticated/classroom/announcements': {
      id: '/_authenticated/classroom/announcements'
      path: '/announcements'
      fullPath: '/classroom/announcements'
      preLoaderRoute: typeof AuthenticatedClassroomAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedClassroomRoute
    }
    '/api/public/voice/turn': {
      id: '/api/public/voice/turn'
      path: '/api/public/voice/turn'
      fullPath: '/api/public/voice/turn'
      preLoaderRoute: typeof ApiPublicVoiceTurnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/voice/status': {
      id: '/api/public/voice/status'
      path: '/api/public/voice/status'
      fullPath: '/api/public/voice/status'
      preLoaderRoute: typeof ApiPublicVoiceStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/voice/start': {
      id: '/api/public/voice/start'
      path: '/api/public/voice/start'
      fullPath: '/api/public/voice/start'
      preLoaderRoute: typeof ApiPublicVoiceStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/study-notes/stream': {
      id: '/api/public/study-notes/stream'
      path: '/api/public/study-notes/stream'
      fullPath: '/api/public/study-notes/stream'
      preLoaderRoute: typeof ApiPublicStudyNotesStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/voice-dispatcher': {
      id: '/api/public/hooks/voice-dispatcher'
      path: '/api/public/hooks/voice-dispatcher'
      fullPath: '/api/public/hooks/voice-dispatcher'
      preLoaderRoute: typeof ApiPublicHooksVoiceDispatcherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/classroom-sync': {
      id: '/api/public/hooks/classroom-sync'
      path: '/api/public/hooks/classroom-sync'
      fullPath: '/api/public/hooks/classroom-sync'
      preLoaderRoute: typeof ApiPublicHooksClassroomSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/classroom/callback': {
      id: '/api/public/classroom/callback'
      path: '/api/public/classroom/callback'
      fullPath: '/api/public/classroom/callback'
      preLoaderRoute: typeof ApiPublicClassroomCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/revision/$setId/summary': {
      id: '/_authenticated/revision/$setId/summary'
      path: '/summary'
      fullPath: '/revision/$setId/summary'
      preLoaderRoute: typeof AuthenticatedRevisionSetIdSummaryRouteImport
      parentRoute: typeof AuthenticatedRevisionSetIdRoute
    }
    '/_authenticated/revision/$setId/session': {
      id: '/_authenticated/revision/$setId/session'
      path: '/session'
      fullPath: '/revision/$setId/session'
      preLoaderRoute: typeof AuthenticatedRevisionSetIdSessionRouteImport
      parentRoute: typeof AuthenticatedRevisionSetIdRoute
    }
    '/_authenticated/revision/$setId/notes': {
      id: '/_authenticated/revision/$setId/notes'
      path: '/notes'
      fullPath: '/revision/$setId/notes'
      preLoaderRoute: typeof AuthenticatedRevisionSetIdNotesRouteImport
      parentRoute: typeof AuthenticatedRevisionSetIdRoute
    }
    '/_authenticated/revision/$setId/known': {
      id: '/_authenticated/revision/$setId/known'
      path: '/known'
      fullPath: '/revision/$setId/known'
      preLoaderRoute: typeof AuthenticatedRevisionSetIdKnownRouteImport
      parentRoute: typeof AuthenticatedRevisionSetIdRoute
    }
    '/_authenticated/revision/$setId/flashcards': {
      id: '/_authenticated/revision/$setId/flashcards'
      path: '/flashcards'
      fullPath: '/revision/$setId/flashcards'
      preLoaderRoute: typeof AuthenticatedRevisionSetIdFlashcardsRouteImport
      parentRoute: typeof AuthenticatedRevisionSetIdRoute
    }
    '/_authenticated/revision/$setId/ask': {
      id: '/_authenticated/revision/$setId/ask'
      path: '/ask'
      fullPath: '/revision/$setId/ask'
      preLoaderRoute: typeof AuthenticatedRevisionSetIdAskRouteImport
      parentRoute: typeof AuthenticatedRevisionSetIdRoute
    }
    '/_authenticated/revision/$setId/topic/$noteId': {
      id: '/_authenticated/revision/$setId/topic/$noteId'
      path: '/topic/$noteId'
      fullPath: '/revision/$setId/topic/$noteId'
      preLoaderRoute: typeof AuthenticatedRevisionSetIdTopicNoteIdRouteImport
      parentRoute: typeof AuthenticatedRevisionSetIdRoute
    }
    '/_authenticated/revision/$setId/notes/new': {
      id: '/_authenticated/revision/$setId/notes/new'
      path: '/new'
      fullPath: '/revision/$setId/notes/new'
      preLoaderRoute: typeof AuthenticatedRevisionSetIdNotesNewRouteImport
      parentRoute: typeof AuthenticatedRevisionSetIdNotesRoute
    }
  }
}

interface AuthenticatedClassroomRouteChildren {
  AuthenticatedClassroomAnnouncementsRoute: typeof AuthenticatedClassroomAnnouncementsRoute
  AuthenticatedClassroomAssignmentsRoute: typeof AuthenticatedClassroomAssignmentsRoute
  AuthenticatedClassroomSettingsRoute: typeof AuthenticatedClassroomSettingsRoute
  AuthenticatedClassroomIndexRoute: typeof AuthenticatedClassroomIndexRoute
}

const AuthenticatedClassroomRouteChildren: AuthenticatedClassroomRouteChildren =
  {
    AuthenticatedClassroomAnnouncementsRoute:
      AuthenticatedClassroomAnnouncementsRoute,
    AuthenticatedClassroomAssignmentsRoute:
      AuthenticatedClassroomAssignmentsRoute,
    AuthenticatedClassroomSettingsRoute: AuthenticatedClassroomSettingsRoute,
    AuthenticatedClassroomIndexRoute: AuthenticatedClassroomIndexRoute,
  }

const AuthenticatedClassroomRouteWithChildren =
  AuthenticatedClassroomRoute._addFileChildren(
    AuthenticatedClassroomRouteChildren,
  )

interface AuthenticatedRevisionSetIdNotesRouteChildren {
  AuthenticatedRevisionSetIdNotesNewRoute: typeof AuthenticatedRevisionSetIdNotesNewRoute
}

const AuthenticatedRevisionSetIdNotesRouteChildren: AuthenticatedRevisionSetIdNotesRouteChildren =
  {
    AuthenticatedRevisionSetIdNotesNewRoute:
      AuthenticatedRevisionSetIdNotesNewRoute,
  }

const AuthenticatedRevisionSetIdNotesRouteWithChildren =
  AuthenticatedRevisionSetIdNotesRoute._addFileChildren(
    AuthenticatedRevisionSetIdNotesRouteChildren,
  )

interface AuthenticatedRevisionSetIdRouteChildren {
  AuthenticatedRevisionSetIdAskRoute: typeof AuthenticatedRevisionSetIdAskRoute
  AuthenticatedRevisionSetIdFlashcardsRoute: typeof AuthenticatedRevisionSetIdFlashcardsRoute
  AuthenticatedRevisionSetIdKnownRoute: typeof AuthenticatedRevisionSetIdKnownRoute
  AuthenticatedRevisionSetIdNotesRoute: typeof AuthenticatedRevisionSetIdNotesRouteWithChildren
  AuthenticatedRevisionSetIdSessionRoute: typeof AuthenticatedRevisionSetIdSessionRoute
  AuthenticatedRevisionSetIdSummaryRoute: typeof AuthenticatedRevisionSetIdSummaryRoute
  AuthenticatedRevisionSetIdTopicNoteIdRoute: typeof AuthenticatedRevisionSetIdTopicNoteIdRoute
}

const AuthenticatedRevisionSetIdRouteChildren: AuthenticatedRevisionSetIdRouteChildren =
  {
    AuthenticatedRevisionSetIdAskRoute: AuthenticatedRevisionSetIdAskRoute,
    AuthenticatedRevisionSetIdFlashcardsRoute:
      AuthenticatedRevisionSetIdFlashcardsRoute,
    AuthenticatedRevisionSetIdKnownRoute: AuthenticatedRevisionSetIdKnownRoute,
    AuthenticatedRevisionSetIdNotesRoute:
      AuthenticatedRevisionSetIdNotesRouteWithChildren,
    AuthenticatedRevisionSetIdSessionRoute:
      AuthenticatedRevisionSetIdSessionRoute,
    AuthenticatedRevisionSetIdSummaryRoute:
      AuthenticatedRevisionSetIdSummaryRoute,
    AuthenticatedRevisionSetIdTopicNoteIdRoute:
      AuthenticatedRevisionSetIdTopicNoteIdRoute,
  }

const AuthenticatedRevisionSetIdRouteWithChildren =
  AuthenticatedRevisionSetIdRoute._addFileChildren(
    AuthenticatedRevisionSetIdRouteChildren,
  )

interface AuthenticatedRevisionRouteChildren {
  AuthenticatedRevisionSetIdRoute: typeof AuthenticatedRevisionSetIdRouteWithChildren
  AuthenticatedRevisionIndexRoute: typeof AuthenticatedRevisionIndexRoute
}

const AuthenticatedRevisionRouteChildren: AuthenticatedRevisionRouteChildren = {
  AuthenticatedRevisionSetIdRoute: AuthenticatedRevisionSetIdRouteWithChildren,
  AuthenticatedRevisionIndexRoute: AuthenticatedRevisionIndexRoute,
}

const AuthenticatedRevisionRouteWithChildren =
  AuthenticatedRevisionRoute._addFileChildren(
    AuthenticatedRevisionRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAiCallsRoute: typeof AuthenticatedAiCallsRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedClassroomRoute: typeof AuthenticatedClassroomRouteWithChildren
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedPomodoroRoute: typeof AuthenticatedPomodoroRoute
  AuthenticatedPowerNapRoute: typeof AuthenticatedPowerNapRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReminderRoute: typeof AuthenticatedReminderRoute
  AuthenticatedRevisionRoute: typeof AuthenticatedRevisionRouteWithChildren
  AuthenticatedVoiceCallNewRoute: typeof AuthenticatedVoiceCallNewRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAiCallsRoute: AuthenticatedAiCallsRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedClassroomRoute: AuthenticatedClassroomRouteWithChildren,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedPomodoroRoute: AuthenticatedPomodoroRoute,
  AuthenticatedPowerNapRoute: AuthenticatedPowerNapRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReminderRoute: AuthenticatedReminderRoute,
  AuthenticatedRevisionRoute: AuthenticatedRevisionRouteWithChildren,
  AuthenticatedVoiceCallNewRoute: AuthenticatedVoiceCallNewRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
  WelcomeRoute: WelcomeRoute,
  ApiChatRoute: ApiChatRoute,
  ApiPublicClassroomCallbackRoute: ApiPublicClassroomCallbackRoute,
  ApiPublicHooksClassroomSyncRoute: ApiPublicHooksClassroomSyncRoute,
  ApiPublicHooksVoiceDispatcherRoute: ApiPublicHooksVoiceDispatcherRoute,
  ApiPublicStudyNotesStreamRoute: ApiPublicStudyNotesStreamRoute,
  ApiPublicVoiceStartRoute: ApiPublicVoiceStartRoute,
  ApiPublicVoiceStatusRoute: ApiPublicVoiceStatusRoute,
  ApiPublicVoiceTurnRoute: ApiPublicVoiceTurnRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
